// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzokJdwhKi5LG8hVKMzgxkWYiwN1HergQ',
    appId: '1:51839895505:web:69478614457bf8f39b82f0',
    messagingSenderId: '51839895505',
    projectId: 'gf-alarm-api',
    authDomain: 'gf-alarm-api.firebaseapp.com',
    storageBucket: 'gf-alarm-api.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjDNu3KGZVoMGG-4n5Yf8tS9lJBO5Km4',
    appId: '1:51839895505:android:788917a8c7d1e9a79b82f0',
    messagingSenderId: '51839895505',
    projectId: 'gf-alarm-api',
    storageBucket: 'gf-alarm-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ZR2kYLCYZSIt6PCXHOOw1EmZZ1VJNrU',
    appId: '1:51839895505:ios:b181393d863a6c9b9b82f0',
    messagingSenderId: '51839895505',
    projectId: 'gf-alarm-api',
    storageBucket: 'gf-alarm-api.firebasestorage.app',
    iosBundleId: 'com.example.gfAlarmApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ZR2kYLCYZSIt6PCXHOOw1EmZZ1VJNrU',
    appId: '1:51839895505:ios:b181393d863a6c9b9b82f0',
    messagingSenderId: '51839895505',
    projectId: 'gf-alarm-api',
    storageBucket: 'gf-alarm-api.firebasestorage.app',
    iosBundleId: 'com.example.gfAlarmApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzokJdwhKi5LG8hVKMzgxkWYiwN1HergQ',
    appId: '1:51839895505:web:86668831a5bc8eec9b82f0',
    messagingSenderId: '51839895505',
    projectId: 'gf-alarm-api',
    authDomain: 'gf-alarm-api.firebaseapp.com',
    storageBucket: 'gf-alarm-api.firebasestorage.app',
  );
}
